In [1]:
import ouroboros as ob

In [2]:
# large dataset of US National Highway System roads
# https://hepgis-usdot.hub.arcgis.com/datasets/dce9f09392eb474c8ad8e6a78416279b_0
gdb_file = "NHS.gdb"

In [3]:
gdb = ob.GeoDatabase(gdb_file)
gdb.feature_classes

['National_Highway_System__NHS_']

In [4]:
# get a feature class from a geodatabase by name or by index
fc = gdb["National_Highway_System__NHS_"]
print(f"Feature class '{fc.name}' contains {len(fc)} rows")

fc = gdb[0]
print(f"Feature class '{fc.name}' contains {len(fc)} rows")

Feature class 'National_Highway_System__NHS_' contains 491781 rows
Feature class 'National_Highway_System__NHS_' contains 491781 rows

In [5]:
# access a feature class directly
fc = ob.FeatureClass("National_Highway_System__NHS_", src="NHS.gdb")
print(f"Feature class '{fc.name}' contains {len(fc)} rows")

Feature class 'National_Highway_System__NHS_' contains 491781 rows

In [6]:
# access a row by index
fc[100]

,VERSION,YEAR,STFIPS,CTFIPS,ROUTEID,BEGINPOINT,ENDPOINT,SIGN1,SIGNT1,SIGNN1,...,AADT_COM,AADT_SINGL,FUT_AADT,FUT_YEAR,MILES,UPDATE_DAT,NHS_ACTION,FILE_NAME,SHAPE_Length,geometry
ObjectID,,,,,,,,,,,,,,,,,,,,,
100,2025.03.27,2020.0,15.0,1.0,19,0.0,99.49,S19,S,19,...,283.0,477.0,12439.0,2039-12-31 00:00:00+00:00,0.080054,NaT,,HI_NHS_2021,137.221299,"MULTILINESTRING ((-17364683.229 2250312.543, -..."

In [7]:
# access multiple rows with slices
fc[100:105]

,VERSION,YEAR,STFIPS,CTFIPS,ROUTEID,BEGINPOINT,ENDPOINT,SIGN1,SIGNT1,SIGNN1,...,AADT_COM,AADT_SINGL,FUT_AADT,FUT_YEAR,MILES,UPDATE_DAT,NHS_ACTION,FILE_NAME,SHAPE_Length,geometry
ObjectID,,,,,,,,,,,,,,,,,,,,,
100,2025.03.27,2020.0,15.0,1.0,19,0.00,99.49,S19,S,19,...,283.0,477.0,12439.0,2039-12-31 00:00:00+00:00,0.080054,NaT,,HI_NHS_2021,137.221299,"MULTILINESTRING ((-17364683.229 2250312.543, -..."
101,2025.03.27,2020.0,15.0,1.0,11,109.22,121.98,S11,S,11,...,43.0,143.0,16415.0,2039-12-31 00:00:00+00:00,1.669810,NaT,,HI_NHS_2021,2864.952720,"MULTILINESTRING ((-17356980.144 2216289.682, -..."
102,2025.03.27,2020.0,15.0,1.0,11,109.22,121.98,S11,S,11,...,135.0,510.0,14235.0,2039-12-31 00:00:00+00:00,0.799934,NaT,,HI_NHS_2021,1367.716107,"MULTILINESTRING ((-17355662.901 2212476.002, -..."
103,2025.03.27,2020.0,15.0,1.0,11,109.22,121.98,S11,S,11,...,104.0,403.0,14106.0,2039-12-31 00:00:00+00:00,1.803699,NaT,,HI_NHS_2021,3096.313308,"MULTILINESTRING ((-17356783.999 2213237.425, -..."
104,2025.03.27,2020.0,15.0,1.0,11,109.22,121.98,S11,S,11,...,261.0,984.0,23853.0,2039-12-31 00:00:00+00:00,1.999768,NaT,,HI_NHS_2021,3431.974770,"MULTILINESTRING ((-17360901.373 2224356.153, -..."

In [14]:
# access multiple rows with a mix of slices and indexes
fc[10, 100:102, 200, 300:302]

,VERSION,YEAR,STFIPS,CTFIPS,ROUTEID,BEGINPOINT,ENDPOINT,SIGN1,SIGNT1,SIGNN1,...,AADT_COM,AADT_SINGL,FUT_AADT,FUT_YEAR,MILES,UPDATE_DAT,NHS_ACTION,FILE_NAME,SHAPE_Length,geometry
0,2025.03.27,2020.0,15.0,9.0,32,0.0,2.850,S32,S,32,...,41.0,175.0,14046.0,2039-12-31 00:00:00+00:00,0.160367,NaT,,HI_NHS_2021,276.205019,"MULTILINESTRING ((-17421669.343 2378509.176, -..."
1,2025.03.27,2020.0,15.0,1.0,19,0.0,99.490,S19,S,19,...,283.0,477.0,12439.0,2039-12-31 00:00:00+00:00,0.160109,NaT,,HI_NHS_2021,274.472320,"MULTILINESTRING ((-17364788.092 2250224.04, -1..."
2,2025.03.27,2020.0,15.0,1.0,19,0.0,99.490,S19,S,19,...,283.0,477.0,12439.0,2039-12-31 00:00:00+00:00,0.080054,NaT,,HI_NHS_2021,137.221299,"MULTILINESTRING ((-17364683.229 2250312.543, -..."
3,2025.03.27,2020.0,15.0,3.0,,0.0,0.123,,,,...,11.0,112.0,1132.0,2037-12-01 00:00:00+00:00,0.127383,2021-05-10 00:00:00+00:00,,HI_NHS_2021,220.613757,"MULTILINESTRING ((-17601280.663 2429863.795, -..."
4,2025.03.27,2020.0,15.0,3.0,H-1,0.0,27.160,IH1,I,1,...,2012.0,33406.0,165421.0,2039-12-31 00:00:00+00:00,0.469948,NaT,,HI_NHS_2021,812.164010,"MULTILINESTRING ((-17589088.173 2439445.206, -..."
5,2025.03.27,2020.0,15.0,3.0,H-1,0.0,27.160,IH1,I,1,...,1601.0,18373.0,215309.0,2039-12-31 00:00:00+00:00,0.155034,NaT,,HI_NHS_2021,267.935861,"MULTILINESTRING ((-17588118.358 2439459.912, -..."

In [9]:
# access multiple rows with a list of indexes
fc[100, 200, 300]
fc[[100, 200, 300]]
fc[(100, 200, 300)]

,VERSION,YEAR,STFIPS,CTFIPS,ROUTEID,BEGINPOINT,ENDPOINT,SIGN1,SIGNT1,SIGNN1,...,AADT_COM,AADT_SINGL,FUT_AADT,FUT_YEAR,MILES,UPDATE_DAT,NHS_ACTION,FILE_NAME,SHAPE_Length,geometry
ObjectID,,,,,,,,,,,,,,,,,,,,,
100,2025.03.27,2020.0,15.0,1.0,19,0.0,99.490,S19,S,19,...,283.0,477.0,12439.0,2039-12-31 00:00:00+00:00,0.080054,NaT,,HI_NHS_2021,137.221299,"MULTILINESTRING ((-17364683.229 2250312.543, -..."
200,2025.03.27,2020.0,15.0,3.0,,0.0,0.316,,,,...,52.0,100.0,1638.0,2037-12-01 00:00:00+00:00,0.315845,2021-05-10 00:00:00+00:00,,HI_NHS_2021,547.042710,"MULTILINESTRING ((-17601243.037 2429815.638, -..."
300,2025.03.27,2020.0,15.0,3.0,H-1,0.0,27.160,IH1,I,1,...,1601.0,18373.0,215309.0,2039-12-31 00:00:00+00:00,0.155034,NaT,,HI_NHS_2021,267.935861,"MULTILINESTRING ((-17588118.358 2439459.912, -..."

In [10]:
# iterate over rows
for row in fc:
    print(row)
    break  # remove this line to print all rows

Pandas(Index=0, VERSION='2025.03.27', YEAR=2020.0, STFIPS=2.0, CTFIPS=290.0, ROUTEID='1260000X000', BEGINPOINT=157.02, ENDPOINT=176.061, SIGN1='S11', SIGNT1='S', SIGNN1='11', LNAME='James Dalton Hwy', NHS=7.0, STATUS=1.0, FACID=' ', CONNID=' ', CONNDES=' ', CONNMILES=0.0, ACLASS='P', FCLASS=3.0, FACILITYT=2.0, THROUGH_LA=2.0, SPEED_LIMI=50.0, OWNERSHIP=1.0, URBANCODE=99999.0, AADT=140.0, AADT_COM=55.0, AADT_SINGL=49.0, FUT_AADT=290.0, FUT_YEAR=Timestamp('2039-12-31 00:00:00+0000', tz='UTC'), MILES=17.912424, UPDATE_DAT=NaT, NHS_ACTION=' ', FILE_NAME='AK_NHS_2021', SHAPE_Length=74037.91898672089, geometry=<MULTILINESTRING ((-16730147.862 10161196.294, -16730142.185 10161213.971, -...>)

In [11]:
# access columns by index
field_name = 'MILES'
column_index = fc.fields.index(field_name)
print(f"The field '{field_name}' is at row index {column_index}:")

for row in fc:
    # print(row[column_index])
    print(row[30])
    break  # remove this line to print all rows

The field 'MILES' is at row index 30:
17.912424